manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: heyjva
      url-base: https://github.com/heyjva
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk-view-trackpad
      remote: heyjva
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config